name: Publish earnapp image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the docker image
        run: docker build -t fazalfarhan01/earnapp:latest -t fazalfarhan01/earnapp:$(date +%y%m%d) app

      - name: Docker Push
        run: docker push fazalfarhan01/earnapp