name: Publish Multiarch Image

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *' # RUN @9AM Everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Download EarnApp
        run: wget -cq https://brightdata.com/static/earnapp/bin_64 -O ./earnapp && chmod a+x ./earnapp
      
      - name: Get version
        run: echo $(./earnapp --version) > ./version

      - name: Remove escape sequences
        run: sudo apt install dos2unix -y && dos2unix ./version

      - name: Build & push
        run: |
          docker buildx build --push \
          -t fazalfarhan01/earnapp:latest \
          -t fazalfarhan01/earnapp:$(cat ./version) \
          --platform linux/amd64,linux/arm/v7 app
