name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the docker image
        run: docker build -t fazalfarhan01/earnapp:latest app

      - name: Get version
        run: echo $(docker run -it --rm fazalfarhan01/earnapp:latest /download/earnapp --version) > version
      
      - name: Remove escape sequences
        run: sudo apt install dos2unix -y && dos2unix version
        
      - name: Tag Image
        run: docker tag fazalfarhan01/earnapp:latest fazalfarhan01/earnapp:$(cat version)
