name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Download EarnApp
        run: wget -c https://brightdata.com/static/earnapp/bin_64 -O ./earnapp && chmod a+x ./earnapp
      
      - name: Get version
        run: echo $(./earnapp --version) > version

      - name: Remove escape sequences
        run: sudo apt install dos2unix -y && dos2unix ./version

      - name: Build the docker image
        run: docker build -t fazalfarhan01/earnapp:latest -t fazalfarhan01/earnapp:$(cat ./version) app
